export const monsters = {
  meleeGrunt: {
    id: "meleeGrunt",
    kind: "monster",
    hp: 220,
    atk: 18,
    defense: 3,
    moveSpeed: 3,
    range: 1.5,
    ai: "rush",
    drops: "common",
  },
  rangedShooter: {
    id: "rangedShooter",
    kind: "monster",
    hp: 160,
    atk: 14,
    defense: 2,
    moveSpeed: 2.5,
    range: 8,
    ai: "kite",
    drops: "common",
  },
  eliteBrute: {
    id: "eliteBrute",
    kind: "monster",
    hp: 520,
    atk: 32,
    defense: 6,
    moveSpeed: 2.2,
    range: 2,
    ai: "rush",
    drops: "elite",
  },
};
